CREATE TABLE STUDENT (
    ID VARCHAR2(10) PRIMARY KEY,
    NAME VARCHAR(30),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MATH NUMBER(3)
);

INSERT INTO STUDENT (ID, NAME, KOR, ENG, MATH)
VALUES ('2020001', '홍길동', 100, 90, 80);

COMMIT;

UPDATE STUDENT
    SET KOR = 99, ENG = 88, MATH = 77
WHERE ID = '2020001';

SELECT ID, NAME, KOR, ENG, MATH
FROM STUDENT
WHERE ID = '2020001';
-- UPDATE 나 DELETE 는 WHERE절로 삭제하거나 바꿀 내용 찾아 쓰기
DELETE FROM STUDENT WHERE ID = '2020001';
---------------------------------------------